// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MierzepAPIv2.Persistance;

namespace MierzepAPIv2.Persistance.Migrations
{
    [DbContext(typeof(TextDBContext))]
    [Migration("20220123194123_RefactoringV1")]
    partial class RefactoringV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InActivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InActivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 1, 23, 20, 41, 22, 666, DateTimeKind.Local).AddTicks(2147),
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zdrowie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biznes"
                        });
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("Empty");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InActivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InActivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Texts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Jak zdrowo się odżywiasz to będziesz dobrze się czuł!",
                            Created = new DateTime(2022, 1, 23, 20, 41, 22, 669, DateTimeKind.Local).AddTicks(6551),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "Spółka wypracowała bardzo duże zyski w tym miesiącu.",
                            Created = new DateTime(2022, 1, 23, 20, 41, 22, 669, DateTimeKind.Local).AddTicks(6742),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "Polska gospodarka przychamowała rozwój i odnotowuje straty.",
                            Created = new DateTime(2022, 1, 23, 20, 41, 22, 669, DateTimeKind.Local).AddTicks(6755),
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Ciągle boli go głowa jakby się rozchorował.",
                            Created = new DateTime(2022, 1, 23, 20, 41, 22, 669, DateTimeKind.Local).AddTicks(6760),
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Author", b =>
                {
                    b.OwnsOne("MierzepAPIv2.Domain.ValueObjects.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<int>("AuthorId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("AuthorId");

                            b1.ToTable("Authors");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");

                            b1.HasData(
                                new
                                {
                                    AuthorId = 1,
                                    FirstName = "Patryk",
                                    LastName = "Mierzejewski"
                                });
                        });

                    b.Navigation("PersonName");
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Text", b =>
                {
                    b.HasOne("MierzepAPIv2.Domain.Entities.Author", "Author")
                        .WithMany("Texts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MierzepAPIv2.Domain.Entities.Category", "Category")
                        .WithMany("Texts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Author", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("MierzepAPIv2.Domain.Entities.Category", b =>
                {
                    b.Navigation("Texts");
                });
#pragma warning restore 612, 618
        }
    }
}
